### ISSUE TITLE
Tests fail on travis but shown as passing

### ISSUE THREAD

**Issue by adri** [debops/ansible-tinc#6]
Thanks a lot! I'm checking out debops and so far it is pretty awesome.

Just a heads up. The tests on travis fail because the nodes can't find each other. The tests are marked as successful though!
https://travis-ci.org/debops/ansible-tinc

```
NOTIFIED: [ansible-tinc | Reload tinc configuration] ************************** 
failed: [localhost] => {"changed": true, "cmd": ["tincd", "-n", "mesh0", "-kHUP"], "delta": "0:00:00.013472", "end": "2015-08-27 14:37:46.808564", "rc": 1, "start": "2015-08-27 14:37:46.795092", "warnings": []}
stderr: No other tincd is running for net `mesh0'.
```

I had the same issue locally, but after setting the connection type to static like described in the docs, it worked.

```
tinc_connection_type: 'static'
```

This is already [set in the test-suite](https://github.com/debops/test-suite/blob/master/ansible-tinc/inventory/group_vars/all/tinc/all.yml), though.

**Comment by drybjed** [comment]
I don't think that Travis allows for setting up custom network interfaces in containers, but I will investigate this at some point.
